### ISSUE TITLE
Fallback icon theme

### ISSUE THREAD

**Issue by Aman9das** [Donnnno/Arcticons-Linux#1]
Creating every icon from scratch is difficult, a good icon pack could be arcticon-ified as a base..

i tried papyrus but their svg's are a mess, they create multiple paths and fill intersections with color, so making fill:none and stroke:white creates a tangle, nothing else..

it would be great if you choose what icon pack we should use as base.. i'll try to write a script to make it with white-lines n no fill...

**Comment by Aman9das** [comment]
how about vimix..?
https://github.com/snwh/paper-icon-theme

**Comment by Donnnno** [comment]
Looks good! I'll send you a collaborator invite, so you can do things without waiting for me (I'm kinda busy this week)

**Comment by Donnnno** [comment]
We already have a solid base of icons in our icon pack, we probably also could use the raster scripts and change them for different resolutions on Linux.

**Comment by Aman9das** [comment]
> We already have a solid base of icons in our icon pack, we probably also could use the raster scripts and change them for different resolutions on Linux.

I couldnt find any raster script to populate the other folders but i think it's better to filter out obviously unnecesary icons... i will try to delete some obvious non linux icons.

And please add the raster scripts functionality in tools folder..

**Comment by Donnnno** [comment]
I can change the raster script for the android version I think

**Comment by Donnnno** [comment]
Should I configure the script so that I rasters the icons in all these resolutions? 

Also a typo in 24x22?

![image](https://user-images.githubusercontent.com/31142286/132124498-30dae973-5429-45bc-92d8-e3bdd701086e.png)

**Comment by Donnnno** [comment]
I've added a raster.sh script, Right now you probably have to add it in the SVG folder to raster it, but it does it job (kinda slow), I can let on my pc or laptop to raster everything overnight ;)

**Comment by Aman9das** [comment]
No its alright just put in tools folder, i'll create a script based on it..

**Comment by Donnnno** [comment]
If we ever want to continue this:
Delta has a good base too:
https://github.com/Delta-Icons/Linux

**Comment by Donnnno** [comment]
Closing this old issue because we have a fresh reboot for a while now!
