### ISSUE TITLE
"Error: unknown shorthand flag: 'c' in -cM" when executing ./generate-manual.sh

### ISSUE THREAD

**Issue by supertsy5** [Donnnno/Arcticons-Linux#17]
```
$ ./generate-manual.sh
inkscape is /usr/bin/inkscape
scour is /usr/bin/scour
(yaml)
Error: unknown shorthand flag: 'c' in -cM
Usage:
  yq eval [expression] [yaml_file1]... [flags]
...
```

**Comment by autinerd** [comment]
Which version of yq do you have? (`yq --version`)

**Comment by supertsy5** [comment]
```
yq (https://github.com/mikefarah/yq/) version 4.35.2
jq-1.6
```

**Comment by autinerd** [comment]
Oh okay, there are two different `yq`. Then we will have to implement that both `yq`s are supported.

**Comment by supertsy5** [comment]
Thank you for helping me.
BTW after switch to yq 3.2.3 (from pip) I encountered another error:
```
inkscape is /usr/bin/inkscape
scour is /usr/bin/scour
mapping.yaml is valid
jq: Unknown option --raw-output0
...
```

**Comment by autinerd** [comment]
Ah, that option was added in jq 1.7, so we will have to look as this as well to support older jq versions.

**Comment by supertsy5** [comment]
> Ah, that option was added in jq 1.7, so we will have to look as this as well to support older jq versions.

Maybe no need to do so, just tell everyone to use the latese version of `jq` :smile_cat:

**Comment by supertsy5** [comment]
And we should provide a list of required tool versions rather than let the script make incomprehensible errors again and again.

As far as I know (assuming that they are using semantic versions):
|Name|Version|
|----|-------|
|jq|^1.7|
|xmlstarlet|^1.6.1|
|yq(*)|^3.2.3|

Note: `yq` should be <https://github.com/kislyuk/yq>(in Python) instead of <https://github.com/mikefarah/yq>(in Go)

**Comment by autinerd** [comment]
So, the mapping scripts now support both `yq` programs and jq < 1.7 :)
