### ISSUE TITLE
Unable to apply to some flatpaks

### ISSUE THREAD

**Issue by GaensebIume** [Donnnno/Arcticons-Linux#31]
When trying to manually change the icon of (some) flatpaks (in this case Signal), I get the error:

Could not save properties due to insufficient write access to:
/home/USERNAME/.local/share/applications/org.signal.Signal.desktop

I am using Fedora 39 with KDE. Strangely, the iconpack was applied to inkscape, which is also installed as a flatpak. 
Creating a new .desktop file seems like a non-ideal workaround.

**Comment by sertonix** [comment]
Some icon names are changed in flatpaks cause they have a strict naming policy.

Could you try if add a mapping to `apps/org.signal.Signal` fixes the problem without changing the icon?

**Comment by autinerd** [comment]
We just need what the icon is called in the desktop-file, then we can add the mapping.

Inkscape works, because the mapping to `org.inkscape.Inkscape` is there.
