### ISSUE TITLE
Authors and contributors file

### ISSUE THREAD

**Issue by Aman9das** [Donnnno/Arcticons-Linux#6]
We should fill it up after looking at some other icon theme..

I have used code made by the papyrus icon theme team (entire tools folder)

And contributors we need to acknowledge the entire frost icon pack and arcticons icon pack...

**Comment by Donnnno** [comment]
Good point, I uhh kinda forgot to do this properly with Arcticons, maybe we can link to the contributors' page of Frost & Arcticons

**Comment by hacknorris-aka-penguin** [comment]
yep good idea

**Comment by Donnnno** [comment]
Closing this old issue because we have a fresh reboot for a while now!
